version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies..
  build:
    commands:
      - echo Installing
      - aws cloudformation package --template-file template.yaml --s3-bucket test-pipeline-artifacts-testing --output-template-file template.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
