version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
  build:
    commands:
      - echo Installing
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
