version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-cfn"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15cs13ccil6r1"
s3_prefix = "test-cfn"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
